
-
  name: 'Article list'
  uriPattern: 'blogexample/articles.{@format}'
  defaults:
    '@package':    'Networkteam.Blogexample'
    '@controller': 'Article'
    '@action':     'index'
    '@format':     'html'

-
  name: 'Article list with custom view'
  uriPattern: 'blogexample/custom/articles.{@format}'
  defaults:
    '@package':    'Networkteam.Blogexample'
    '@controller': 'Article'
    '@action':     'custom'
    '@format':     'html'